
name: Heroku Action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          # Used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # Email from Heroku Account
          heroku_email: "lv_oz2@icloud.com"
          # The appname to use for deploying/updating
          heroku_app_name: "js-irs"
          # The branch that you would like to deploy to Heroku
          branch: "main"
