name: Run PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP environment
        uses: nanasess/setup-php@v3.0.6
        with:
          php-version: '7.4'
      - run: |
